### PR TITLE
Cleaned source code style.

### PR DESCRIPTION
**Pull request by mdtrooper**
Good morning.

I have been cleaning the source code style.

Bye.

### CODE REVIEW

**Comment by vanfanel** [comment]
Thanks, MDTrooper! I didn't pay much attention to the main function because it's just an usage example, but it's nice that you've took a look into my code :+1:

**Comment by mdtrooper** [comment]
Well, Could you acept my pull request?

Bye.

**Comment by vanfanel** [comment]
Done!

**Comment by mdtrooper** [comment]
Thanks :smile:

**Pull request merged**
